baseurl = "/"
languageCode = "en-us"
title = "Classic"
theme = "hugo-software-kit"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/guide/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "steps"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A language agnostic guide to building a web server."
    footer = "Open-Source | [Github](https://github.com/wwkeyboard/webserverkit) | [Twitter](https://twitter.com/wwkeyboard)"
    custom_css = ["css/theme-override.css"]
